
import React, { useState, useEffect } from 'react';
import { Text, View, ScrollView, TouchableOpacity, Alert, Share } from 'react-native';
import { commonStyles, colors } from '../styles/commonStyles';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Icon from '../components/Icon';
import Button from '../components/Button';

interface TestResult {
  id: string;
  testId: string;
  timestamp: number;
  videoUri?: string;
  measurements: any;
  score: number;
  analysis: string;
  confidence?: number;
  detectedMovements?: string[];
  formFeedback?: string[];
  uploadStatus?: 'pending' | 'uploaded' | 'failed';
}

interface UserProfile {
  name: string;
  age: number;
  gender: 'male' | 'female';
  height: number;
  weight: number;
  sport: string;
  level: 'beginner' | 'intermediate' | 'advanced';
}

export default function ExportScreen() {
  const [results, setResults] = useState<TestResult[]>([]);
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      console.log('Loading export data...');
      
      const [resultsData, profileData] = await Promise.all([
        AsyncStorage.getItem('testResults'),
        AsyncStorage.getItem('userProfile')
      ]);

      if (resultsData) {
        const parsedResults = JSON.parse(resultsData);
        console.log('Loaded results for export:', parsedResults);
        setResults(parsedResults);
      }

      if (profileData) {
        const parsedProfile = JSON.parse(profileData);
        console.log('Loaded profile for export:', parsedProfile);
        setProfile(parsedProfile);
      }

      setLoading(false);
    } catch (error) {
      console.log('Error loading export data:', error);
      setLoading(false);
    }
  };

  const getOverallScore = () => {
    if (results.length === 0) return 0;
    const totalScore = results.reduce((sum, result) => sum + result.score, 0);
    return Math.round(totalScore / results.length);
  };

  const generateReport = () => {
    if (!profile) return '';

    const overallScore = getOverallScore();
    const testCount = results.length;
    const avgConfidence = results.reduce((sum, r) => sum + (r.confidence || 0), 0) / testCount;
    const uploadedCount = results.filter(r => r.uploadStatus === 'uploaded').length;

    const report = `
SPORTS AUTHORITY OF INDIA
FITNESS ASSESSMENT REPORT

=================================
ATHLETE INFORMATION
=================================
Name: ${profile.name}
Age: ${profile.age} years
Gender: ${profile.gender}
Height: ${profile.height} cm
Weight: ${profile.weight} kg
Sport: ${profile.sport}
Level: ${profile.level}
BMI: ${(profile.weight / ((profile.height / 100) ** 2)).toFixed(1)}

=================================
ASSESSMENT SUMMARY
=================================
Overall Score: ${overallScore}/100
Tests Completed: ${testCount}
AI Analysis Confidence: ${avgConfidence.toFixed(1)}%
Data Upload Status: ${uploadedCount}/${testCount} uploaded

=================================
DETAILED RESULTS
=================================
${results.map(result => {
  const testNames = {
    'vertical-jump': 'Vertical Jump Test',
    'shuttle-run': 'Shuttle Run Test',
    'sit-ups': 'Sit-ups Test',
    'endurance-run': 'Endurance Run Test',
    'height-weight': 'Height & Weight Measurement'
  };
  
  return `
${testNames[result.testId as keyof typeof testNames] || result.testId}
Date: ${new Date(result.timestamp).toLocaleDateString()}
Score: ${result.score}/100
AI Confidence: ${result.confidence || 'N/A'}%
Analysis: ${result.analysis}
${result.detectedMovements ? `
Detected Movements:
${result.detectedMovements.map(m => `- ${m}`).join('\n')}` : ''}
${result.formFeedback ? `
Form Feedback:
${result.formFeedback.map(f => `- ${f}`).join('\n')}` : ''}
Upload Status: ${result.uploadStatus || 'pending'}
---`;
}).join('\n')}

=================================
AI ANALYSIS SUMMARY
=================================
This report contains AI-powered analysis of fitness assessment videos.
The analysis includes:
- Automated movement detection and counting
- Form and technique evaluation
- Performance benchmarking against age/gender norms
- Personalized feedback and recommendations

All video data has been processed using advanced computer vision
and machine learning algorithms to ensure accurate and objective
assessment of athletic performance.

=================================
RECOMMENDATIONS
=================================
${getRecommendations().map(rec => `- ${rec}`).join('\n')}

Report generated on: ${new Date().toLocaleString()}
Generated by: AI-Powered Sports Assessment Platform
For: Sports Authority of India (SAI)
    `.trim();

    return report;
  };

  const getRecommendations = () => {
    const overallScore = getOverallScore();
    const recommendations = [];

    if (overallScore < 60) {
      recommendations.push('Focus on basic fitness fundamentals and conditioning');
      recommendations.push('Increase training frequency to 4-5 sessions per week');
      recommendations.push('Work with a certified fitness coach for proper form');
      recommendations.push('Emphasize cardiovascular endurance and strength building');
    } else if (overallScore < 80) {
      recommendations.push('Target specific weak areas identified in individual tests');
      recommendations.push('Increase training intensity with interval training');
      recommendations.push('Add sport-specific drills and movements');
      recommendations.push('Consider specialized coaching for technique improvement');
    } else {
      recommendations.push('Maintain current high training standards');
      recommendations.push('Focus on competition preparation and peak performance');
      recommendations.push('Consider advanced training techniques and periodization');
      recommendations.push('Eligible for advanced SAI training programs');
    }

    // Add specific recommendations based on individual test results
    results.forEach(result => {
      if (result.score < 60) {
        switch (result.testId) {
          case 'vertical-jump':
            recommendations.push('Improve explosive power with plyometric exercises');
            break;
          case 'shuttle-run':
            recommendations.push('Work on agility and change of direction drills');
            break;
          case 'sit-ups':
            recommendations.push('Strengthen core muscles with targeted exercises');
            break;
          case 'endurance-run':
            recommendations.push('Build cardiovascular endurance with longer runs');
            break;
        }
      }
    });

    return [...new Set(recommendations)]; // Remove duplicates
  };

  const handleShare = async () => {
    try {
      const report = generateReport();
      await Share.share({
        message: report,
        title: 'Fitness Assessment Report'
      });
      console.log('Report shared successfully');
    } catch (error) {
      console.log('Error sharing report:', error);
      Alert.alert('Error', 'Failed to share report');
    }
  };

  const handleSubmitToSAI = async () => {
    if (!profile) {
      Alert.alert('Error', 'Profile data not available');
      return;
    }

    Alert.alert(
      'Submit to SAI',
      'This will officially submit your fitness assessment data to the Sports Authority of India for evaluation. Are you sure?',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Submit', 
          onPress: async () => {
            setIsSubmitting(true);
            try {
              console.log('Submitting data to SAI...');
              
              // Simulate submission process
              await new Promise(resolve => setTimeout(resolve, 3000));
              
              // Update upload status for all results
              const updatedResults = results.map(result => ({
                ...result,
                uploadStatus: 'uploaded' as const
              }));
              
              await AsyncStorage.setItem('testResults', JSON.stringify(updatedResults));
              setResults(updatedResults);
              
              console.log('Data submitted to SAI successfully');
              
              Alert.alert(
                'Submission Successful',
                'Your fitness assessment data has been successfully submitted to the Sports Authority of India. You will receive confirmation and further instructions via email.',
                [{ text: 'OK' }]
              );
            } catch (error) {
              console.log('Error submitting to SAI:', error);
              Alert.alert('Error', 'Failed to submit data to SAI. Please try again.');
            } finally {
              setIsSubmitting(false);
            }
          }
        }
      ]
    );
  };

  if (loading) {
    return (
      <SafeAreaView style={commonStyles.centerContent}>
        <Icon name="document-text-outline" size={64} color={colors.primary} />
        <Text style={commonStyles.title}>Preparing Report</Text>
        <Text style={commonStyles.textSecondary}>Generating your fitness assessment report...</Text>
      </SafeAreaView>
    );
  }

  if (results.length === 0) {
    return (
      <SafeAreaView style={commonStyles.centerContent}>
        <Icon name="document-outline" size={64} color={colors.textSecondary} />
        <Text style={commonStyles.title}>No Data to Export</Text>
        <Text style={commonStyles.textSecondary}>
          Complete some fitness assessment tests to generate a report.
        </Text>
        <Button
          text="Take a Test"
          onPress={() => router.push('/')}
          style={{ marginTop: 20 }}
        />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={commonStyles.container}>
      <View style={commonStyles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Icon name="arrow-back" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={commonStyles.headerTitle}>Export & Submit</Text>
        <View style={{ width: 24 }} />
      </View>

      <ScrollView style={commonStyles.content}>
        {profile && (
          <View style={commonStyles.card}>
            <Text style={commonStyles.sectionTitle}>Report Summary</Text>
            <View style={[commonStyles.row, { marginBottom: 8 }]}>
              <Text style={commonStyles.text}>Athlete:</Text>
              <Text style={commonStyles.text}>{profile.name}</Text>
            </View>
            <View style={[commonStyles.row, { marginBottom: 8 }]}>
              <Text style={commonStyles.text}>Tests Completed:</Text>
              <Text style={commonStyles.text}>{results.length}</Text>
            </View>
            <View style={[commonStyles.row, { marginBottom: 8 }]}>
              <Text style={commonStyles.text}>Overall Score:</Text>
              <Text style={[commonStyles.text, { 
                color: getOverallScore() > 75 ? colors.success : 
                       getOverallScore() > 60 ? colors.warning : colors.error 
              }]}>
                {getOverallScore()}/100
              </Text>
            </View>
            <View style={commonStyles.row}>
              <Text style={commonStyles.text}>AI Confidence:</Text>
              <Text style={commonStyles.text}>
                {results.length > 0 ? 
                  Math.round(results.reduce((sum, r) => sum + (r.confidence || 0), 0) / results.length) : 0}%
              </Text>
            </View>
          </View>
        )}

        <View style={commonStyles.card}>
          <Text style={commonStyles.sectionTitle}>Upload Status</Text>
          <Text style={commonStyles.text}>
            Track the status of your data submission to the Sports Authority of India:
          </Text>
          
          <View style={{ marginTop: 16 }}>
            <View style={[commonStyles.row, { marginBottom: 12 }]}>
              <View style={[commonStyles.row, { flex: 1 }]}>
                <Icon name="cloud-done-outline" size={20} color={colors.success} />
                <Text style={[commonStyles.text, { marginLeft: 8 }]}>Uploaded</Text>
              </View>
              <Text style={[commonStyles.text, { color: colors.success }]}>
                {results.filter(r => r.uploadStatus === 'uploaded').length}
              </Text>
            </View>
            
            <View style={[commonStyles.row, { marginBottom: 12 }]}>
              <View style={[commonStyles.row, { flex: 1 }]}>
                <Icon name="cloud-upload-outline" size={20} color={colors.warning} />
                <Text style={[commonStyles.text, { marginLeft: 8 }]}>Pending</Text>
              </View>
              <Text style={[commonStyles.text, { color: colors.warning }]}>
                {results.filter(r => r.uploadStatus === 'pending' || !r.uploadStatus).length}
              </Text>
            </View>
            
            <View style={commonStyles.row}>
              <View style={[commonStyles.row, { flex: 1 }]}>
                <Icon name="cloud-offline-outline" size={20} color={colors.error} />
                <Text style={[commonStyles.text, { marginLeft: 8 }]}>Failed</Text>
              </View>
              <Text style={[commonStyles.text, { color: colors.error }]}>
                {results.filter(r => r.uploadStatus === 'failed').length}
              </Text>
            </View>
          </View>
        </View>

        <View style={commonStyles.card}>
          <Text style={commonStyles.sectionTitle}>AI Analysis Features</Text>
          <Text style={commonStyles.text}>
            Your assessment includes advanced AI-powered analysis:
          </Text>
          
          <View style={{ marginTop: 12 }}>
            <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
              <Icon name="eye-outline" size={16} color={colors.primary} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                Computer vision for movement detection and analysis
              </Text>
            </View>
            <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
              <Icon name="analytics-outline" size={16} color={colors.primary} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                Performance benchmarking against demographic norms
              </Text>
            </View>
            <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
              <Icon name="shield-checkmark-outline" size={16} color={colors.primary} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                Anti-cheat detection and video authenticity verification
              </Text>
            </View>
            <View style={[commonStyles.row, { alignItems: 'flex-start' }]}>
              <Icon name="bulb-outline" size={16} color={colors.primary} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                Personalized feedback and improvement recommendations
              </Text>
            </View>
          </View>
        </View>

        <View style={commonStyles.card}>
          <Text style={commonStyles.sectionTitle}>Data Security</Text>
          <Text style={commonStyles.text}>
            Your fitness assessment data is handled with the highest security standards:
          </Text>
          
          <View style={{ marginTop: 12 }}>
            <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
              <Icon name="lock-closed-outline" size={16} color={colors.success} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                End-to-end encryption for all data transmission
              </Text>
            </View>
            <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
              <Icon name="server-outline" size={16} color={colors.success} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                Secure storage on government-approved servers
              </Text>
            </View>
            <View style={[commonStyles.row, { alignItems: 'flex-start' }]}>
              <Icon name="document-lock-outline" size={16} color={colors.success} style={{ marginRight: 8, marginTop: 2 }} />
              <Text style={[commonStyles.textSecondary, { flex: 1 }]}>
                Compliance with data protection regulations
              </Text>
            </View>
          </View>
        </View>

        <View style={[commonStyles.row, { marginTop: 20 }]}>
          <Button
            text="Share Report"
            onPress={handleShare}
            style={[{ flex: 1, marginRight: 8 }, { backgroundColor: colors.secondary }]}
          />
          <Button
            text={isSubmitting ? "Submitting..." : "Submit to SAI"}
            onPress={handleSubmitToSAI}
            style={{ flex: 1, marginLeft: 8 }}
            disabled={isSubmitting}
          />
        </View>

        <View style={{ marginTop: 16, marginBottom: 40 }}>
          <Button
            text="View Detailed Results"
            onPress={() => router.push('/results')}
            variant="outline"
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
