
import React, { useState, useEffect } from 'react';
import { Text, View, ScrollView, TouchableOpacity, Alert, Share } from 'react-native';
import { commonStyles, colors } from '../styles/commonStyles';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Icon from '../components/Icon';
import Button from '../components/Button';

interface TestResult {
  id: string;
  testId: string;
  timestamp: number;
  videoUri?: string;
  measurements: any;
  score: number;
  analysis: string;
}

interface UserProfile {
  name: string;
  age: number;
  gender: 'male' | 'female';
  height: number;
  weight: number;
  sport: string;
  level: 'beginner' | 'intermediate' | 'advanced';
}

const testNames = {
  'vertical-jump': 'Vertical Jump',
  'shuttle-run': 'Shuttle Run',
  'sit-ups': 'Sit-ups',
  'endurance-run': 'Endurance Run',
  'height-weight': 'Height & Weight',
};

export default function ExportScreen() {
  const [results, setResults] = useState<TestResult[]>([]);
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const resultsData = await AsyncStorage.getItem('testResults');
      const profileData = await AsyncStorage.getItem('userProfile');
      
      if (resultsData) {
        setResults(JSON.parse(resultsData));
      }
      
      if (profileData) {
        setProfile(JSON.parse(profileData));
      }
    } catch (error) {
      console.log('Error loading data:', error);
    }
  };

  const generateReport = () => {
    if (!profile || results.length === 0) {
      Alert.alert('Error', 'No data available to generate report');
      return;
    }

    const overallScore = Math.round(
      results.reduce((sum, result) => sum + result.score, 0) / results.length
    );

    const performanceLevel = overallScore >= 85 ? 'Elite' : 
                           overallScore >= 70 ? 'Advanced' : 
                           overallScore >= 55 ? 'Intermediate' : 'Beginner';

    return `
🏆 SAI TALENT SCOUT REPORT 🏆

Athlete: ${profile.name}
Age: ${profile.age} years
Gender: ${profile.gender}
Sport: ${profile.sport}
Experience: ${profile.level}

📊 PERFORMANCE SUMMARY
Overall Score: ${overallScore}/100
Performance Level: ${performanceLevel}
Tests Completed: ${results.length}/5

📋 TEST RESULTS
${results.map(result => `
${testNames[result.testId as keyof typeof testNames]}: ${result.score}/100
${Object.entries(result.measurements).map(([key, value]) => `  ${key}: ${value}`).join('\n')}
Analysis: ${result.analysis}
`).join('\n')}

🎯 RECOMMENDATIONS
${overallScore < 60 ? '• Focus on basic fitness fundamentals\n• Increase training frequency' : 
  overallScore < 80 ? '• Work on sport-specific skills\n• Consider strength programs' : 
  '• Maintain current intensity\n• Focus on competition prep'}

Generated by SAI Talent Scout App
Sports Authority of India
${new Date().toLocaleDateString()}
    `.trim();
  };

  const handleShare = async () => {
    try {
      setIsGenerating(true);
      const report = generateReport();
      
      await Share.share({
        message: report,
        title: 'SAI Talent Scout Report',
      });
    } catch (error) {
      console.log('Error sharing report:', error);
      Alert.alert('Error', 'Failed to share report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmitToSAI = async () => {
    Alert.alert(
      'Submit to SAI',
      'This feature will securely submit your verified performance data to the Sports Authority of India for official evaluation. Your data will be encrypted and transmitted through secure channels.\n\nNote: This is a demo version. In the production app, this would connect to SAI servers.',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Submit', 
          onPress: () => {
            // In a real app, this would submit to SAI backend
            Alert.alert(
              'Submitted Successfully',
              'Your performance data has been submitted to SAI for evaluation. You will receive feedback within 5-7 business days.',
              [{ text: 'OK', onPress: () => router.push('/') }]
            );
          }
        },
      ]
    );
  };

  const getOverallScore = () => {
    if (results.length === 0) return 0;
    return Math.round(results.reduce((sum, result) => sum + result.score, 0) / results.length);
  };

  if (!profile || results.length === 0) {
    return (
      <SafeAreaView style={commonStyles.container}>
        <View style={commonStyles.header}>
          <TouchableOpacity onPress={() => router.back()}>
            <Icon name="arrow-back" size={24} color={colors.text} />
          </TouchableOpacity>
          <Text style={commonStyles.headerTitle}>Export Results</Text>
          <View style={{ width: 24 }} />
        </View>

        <View style={commonStyles.centerContent}>
          <Icon name="document-outline" size={64} color={colors.textSecondary} />
          <Text style={commonStyles.title}>No Data Available</Text>
          <Text style={commonStyles.textSecondary}>
            Complete your profile and some tests to generate and export your report
          </Text>
          <Button
            text="Go Back"
            onPress={() => router.back()}
            style={{ marginTop: 20 }}
          />
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={commonStyles.container}>
      <View style={commonStyles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Icon name="arrow-back" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={commonStyles.headerTitle}>Export Results</Text>
        <View style={{ width: 24 }} />
      </View>

      <ScrollView style={commonStyles.content} showsVerticalScrollIndicator={false}>
        <View style={commonStyles.card}>
          <View style={[commonStyles.row, { marginBottom: 16 }]}>
            <Icon name="document-text" size={32} color={colors.primary} />
            <View style={{ flex: 1, marginLeft: 16 }}>
              <Text style={commonStyles.subtitle}>Performance Report</Text>
              <Text style={commonStyles.textSecondary}>
                Comprehensive analysis of your fitness assessment results
              </Text>
            </View>
          </View>

          <View style={commonStyles.divider} />

          <View style={[commonStyles.row, { marginBottom: 8 }]}>
            <Text style={commonStyles.text}>Athlete:</Text>
            <Text style={[commonStyles.text, { fontWeight: '600' }]}>{profile.name}</Text>
          </View>
          <View style={[commonStyles.row, { marginBottom: 8 }]}>
            <Text style={commonStyles.text}>Overall Score:</Text>
            <Text style={[commonStyles.text, { fontWeight: '600', color: colors.primary }]}>
              {getOverallScore()}/100
            </Text>
          </View>
          <View style={[commonStyles.row, { marginBottom: 8 }]}>
            <Text style={commonStyles.text}>Tests Completed:</Text>
            <Text style={[commonStyles.text, { fontWeight: '600' }]}>{results.length}/5</Text>
          </View>
          <View style={commonStyles.row}>
            <Text style={commonStyles.text}>Generated:</Text>
            <Text style={commonStyles.text}>{new Date().toLocaleDateString()}</Text>
          </View>
        </View>

        <View style={commonStyles.card}>
          <Text style={commonStyles.sectionTitle}>Export Options</Text>
          
          <TouchableOpacity
            style={[
              commonStyles.row,
              {
                paddingVertical: 16,
                borderBottomWidth: 1,
                borderBottomColor: colors.border,
              }
            ]}
            onPress={handleShare}
            disabled={isGenerating}
          >
            <Icon name="share-outline" size={24} color={colors.primary} />
            <View style={{ flex: 1, marginLeft: 16 }}>
              <Text style={commonStyles.text}>Share Report</Text>
              <Text style={commonStyles.textSecondary}>
                Share your performance report via messaging or email
              </Text>
            </View>
            <Icon name="chevron-forward" size={20} color={colors.textSecondary} />
          </TouchableOpacity>

          <TouchableOpacity
            style={[
              commonStyles.row,
              { paddingVertical: 16 }
            ]}
            onPress={handleSubmitToSAI}
          >
            <Icon name="cloud-upload-outline" size={24} color={colors.success} />
            <View style={{ flex: 1, marginLeft: 16 }}>
              <Text style={commonStyles.text}>Submit to SAI</Text>
              <Text style={commonStyles.textSecondary}>
                Securely submit your data to Sports Authority of India
              </Text>
            </View>
            <Icon name="chevron-forward" size={20} color={colors.textSecondary} />
          </TouchableOpacity>
        </View>

        <View style={commonStyles.card}>
          <Text style={commonStyles.sectionTitle}>Data Security</Text>
          <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
            <Icon name="shield-checkmark" size={16} color={colors.success} style={{ marginTop: 2 }} />
            <Text style={[commonStyles.text, { flex: 1, marginLeft: 8 }]}>
              All data is encrypted and transmitted through secure channels
            </Text>
          </View>
          <View style={[commonStyles.row, { marginBottom: 8, alignItems: 'flex-start' }]}>
            <Icon name="lock-closed" size={16} color={colors.success} style={{ marginTop: 2 }} />
            <Text style={[commonStyles.text, { flex: 1, marginLeft: 8 }]}>
              Your personal information is protected according to SAI privacy policies
            </Text>
          </View>
          <View style={[commonStyles.row, { alignItems: 'flex-start' }]}>
            <Icon name="checkmark-circle" size={16} color={colors.success} style={{ marginTop: 2 }} />
            <Text style={[commonStyles.text, { flex: 1, marginLeft: 8 }]}>
              AI-verified performance data ensures authenticity and accuracy
            </Text>
          </View>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}
